### ISSUE TITLE
GitHub Topics only support 'dotnetnuke'

### ISSUE THREAD

**Issue by ahoefling** [nvisionative/nvQuickPulse#8]
# The Problem

I noticed that some DNN repos were not showing up in the nvQuickPulse mobile app that were tagged with items such as

* `dnn`
* `dnncms`

After adding the tag `dotnetnuke` it showed up.

# The Question

Is it by design to only display items tagged as `dotnetnuke`?

**Comment by nvisionative** [comment]
@ahoefling this was a bit of a challenge to deal with.  The GitHub API doesn't work as you would expect.  So, to get the most realistic results, we are using a basic query search (`q=dotnetnuke+<searchTerm>`).  We tried so many different ways and this way pulled in the most relevant results.  You can do a simple experiment by trying the following:

[https://api.github.com/search/repositories?q=dotnetnuke](https://api.github.com/search/repositories?q=dotnetnuke) 
This link produces 386 results as of the writing of this comment.

[https://api.github.com/search/repositories?q=dotnetnuke+dnncms](https://api.github.com/search/repositories?q=dotnetnuke+dnncms)
This link produces 66 results as of the writing of this comment.

We tried topic-based searches, etc. and nothing worked as good as the "Search by repository name, description, or contents of the README file" approach.  

Therefore, we have been actively searching GitHub manually to find various DNN related projects and asking project maintainers to update their descriptions, topics and README files to include "DotNetNuke".  That way we can still find all legacy extensions, as well as newer ones post-brand-change to "DNN".

If you know of any repos that could be updated, please help us create issues/PRs to update.  Thanks!
